### ISSUE TITLE
Copying a file to a container before starting it doesnt respect the file permissions

### ISSUE THREAD

**Issue by the-mentor** [joyrex2001/kubedock#127]
Copying a file to a container before starting it doesnt respect the file's original permissions.
For example,

If a file is executable the file that is inside the container is not executable

the issue can be replicated by having a pod with kubedock as a sidecar 
and running the following code from withing pod 

```
echo 'echo test' > test.sh
chmod +x test.sh
docker create --name my_nginx nginx:latest
docker cp ./test.sh my_nginx:/test.sh
docker start my_nginx

# Run docker exec to see the file permissions and see the that file doesnt have any executable permissions
docker exec my_nginx ls -lh /test.sh
```

example of testcontainers-java code 
`targetContainer.copyFileToContainer(Transferable.of(bytes, 0777), containerFilePath);`

The documenation can be found in the link below under `Copying files using Transferable with file mode`
https://java.testcontainers.org/features/files/

**Comment by the-mentor** [comment]
After some additional research, I found out that we dont specify `DefaultMode` when we create the raw volume so its sets the default to `420` decimal which is `0644` octal 
which sets the permissions to:
User: read, write
Group: Read
Other: Read

From what i can tell we can use the following structure 
```
 volumes:
  - name: config-volume
    configMap:
      name: example-config
      items:
      - key: binary-key1
        path: key1-file
        mode: 0600  # Owner read/write
      - key: binary-key2
        path: key2-file
        mode: 0644  # Owner read/write, others read
```
to grant different files different permissions
