### ISSUE TITLE
Support ephemeral storage resource configuration

### ISSUE THREAD

**Issue by Preetham-MSK** [joyrex2001/kubedock#134]
Hi,

Currently, Kubedock supports configuring CPU and memory resources when spinning up containers, but there doesn't seem to be an option for configuring ephemeral storage resources. I believe this feature would be helpful for workloads that require temporary storage, such as those needing disk space for caching, logs, or other temporary data storage.

Could we add labels and parameters similar to those for CPU and memory, such as:

- Label: `com.joyrex2001.kubedock.request-ephemeral-storage`
- Argument: `--request-ephemeral-storage`

This feature would make Kubedock more flexible and suitable for a wider range of workloads that also rely on ephemeral storage, such as databases with initialized schemas, data processing, or application containers that generate large amounts of temporary data.

**Comment by mrcdnk** [comment]
we also need this, so I created a MR with an attempt at implementing this.

**Comment by mrcdnk** [comment]
For completeness sake, this new `ephemeral-storage` resource configuration should go into the container on the created pod:.

The label `com.joyrex2001.kubedock.request-ephemeral-storage: "256Mi,512Mi"` for example should lead to this Pod being created:

```
apiVersion: v1  
kind: Pod
metadata:  
    name: docker-container-in-kube
    namespace: default  
spec:  
    containers:  
        - name: docker-container-in-kube
          image: nginx:1.21
          [...]
          resources:
              limits:
                 ephemeral-storage: "512Mi"
              requests:
                 ephemeral-storage: "256Mi"
```
