### ISSUE TITLE
Document serviceaccount RBAC configuration

### ISSUE THREAD

**Issue by newsletter-csuite** [joyrex2001/kubedock#14]
I did not found in the Readme how to configure correctly RBAC for serviceaccount.
I personnally found this as a minimal working configuration : 
```
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: kubedock
        rules:
          - apiGroups: ["apps"]
            resources: ["deployments"]
            verbs: ["create", "get", "list", "delete"]
          - apiGroups: [""]
            resources: ["pods", "pods/log"]
            verbs: ["list", "get"]
          - apiGroups: [""]
            resources: ["services"]
            verbs: ["create", "get", "list"]
```

Perhaps it should be mentionned in the doc ?
