### ISSUE TITLE
Verbosity switch is ignored with --pod-template option

### ISSUE THREAD

**Issue by igor-teresco** [joyrex2001/kubedock#83]
According to the manual verbosity flag it should be set after the command:
`/usr/local/bin/kubedock server -v 3` and that works correct.

But when I try to see why a given podTemplate is not accepted by server, that switch is ignored:
`/ # /usr/local/bin/kubedock server -v 3 --pod-template /opt/kubedockpod/kubedockpod.yml
I0328 15:41:11.690608     233 main.go:29] kubedock 0.15.5-6-gcb37b43 (20240327-070255) / kubedock.id=98459b9b4eaa
I0328 15:41:11.692041     233 main.go:109] kubernetes config: namespace=jenkins-k8s, initimage=joyrex2001/kubedock:0.15.5, dindimage=joyrex2001/kubedock:0.15.5, ready timeout=1m0s
I0328 15:41:11.692327     233 main.go:118] kubedock url: http://172.18.0.85:2475
F0328 15:41:11.692759     233 main.go:43] error instantiating backend: error opening podtemplate: invalid podtemplate: /opt/kubedockpod/kubedockpod.yml`

Btw, can somebody show a valid podTemplate file, so I can fix mine?

**Comment by joyrex2001** [comment]
When a pod-template is invalid, kubedock will exit and log a message containing `error instantiating backend: error opening podtemplate: <details of error>`. The verbosity is unaffected, kubedock simply stops running due to the fatal error.

An example for a pod template file would be: 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    example: kubedock 
spec:
  containers:
  - resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
    securityContext:
      allowPrivilegeEscalation: false
```

**Comment by igor-teresco** [comment]
I see, so there is no way to see what exactly is invalid in the given template?
We had to add image definition for kubedock to accept it:
`    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: kubedock
    spec:
      containers:
      - name: kubedock
        image: joyrex2001/kubedock:latest
      priorityClassName: high-priority`

Will try your template

**Comment by joyrex2001** [comment]
The pod template is a regular pod.yaml, which is parsed via the k8s client library. The error that is returned, comes directly from there. Not sure how to improve that behavior (open for ideas).

From a pragmatic point of view, to easily create a template, you can take an existing pod, use that as a basis and strip all non-required fields.

I tested with yours; and this is how I got it to work (maybe it was an indenting issue, hard to tell from your copy-paste):

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubedock
spec:
  containers:
  - name: kubedock
    image: joyrex2001/kubedock:latest
  priorityClassName: high-priority
```

Note that containers can actually be left out (since it will be overwritten with the container that it should start).
